version: "3.8"
services:
  greenheat.server:
    container_name: server
    ## for local build
    build:
      context: ./server
      dockerfile: Dockerfile-server
    ## for production instead of "build:" use "image:" only (before must upload image)
    # image: registry.example.com/greenheat/server:${RELEASE_VERSION}
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      greenheat:
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - SERVER_PROTOCOL=${SERVER_PROTOCOL}
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_NAME=${SERVER_NAME}
      - SERVER_API_PREFIX=${SERVER_API_PREFIX}
  greenheat.webapp:
    container_name: webapp
    ## for local build
    build:
      context: ./webapp
      dockerfile: Dockerfile-webapp
    ## for production instead of "build:" use "image:" only (before must upload image)
    # image: registry.example.com/greenheat/webapp:${RELEASE_VERSION}
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      greenheat:
    environment:
      - PROXY_SERVER_HOST=${SERVER_HOST}
      - PROXY_SERVER_PORT=${SERVER_PORT}
networks:
  greenheat:
    name: greenheat_network
